
language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - 1.7.4

otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 21.0.3
  - 21.2

env:
  - MIX_ENV=test

script: mix coveralls.travis
