
language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.5.1
  - 1.5.2
  - 1.5.3

otp_release:
  - 20.0
  - 20.1
  - 20.2

env:
  - MIX_ENV=test

script: mix coveralls.travis
